server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

auth:
  service:
    url: ${AUTH_URL:http://localhost:8080}

exporter:
  queue:
    name: export-request
    url: http://localhost:9324
    region: local


---
spring:
  config:
    activate:
      on-profile: test

auth:
  service:
    url: http://localhost:${wiremock.server.port}
