server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

  servlet:
    context-path: ${BASE_PATH:}

service:
  url: ${SERVICE_URL:http://localhost:3000}
  auth:
    key: ${SERVICE_AUTH_KEY}

exporter:
  enabled: ${EXPORTER_ENABLED:true}
  queue:
    name: ${EXPORTER_QUEUE_NAME:export-request}
    url: ${EXPORTER_QUEUE_URL:http://localhost:9324}
    region: ${EXPORTER_QUEUE_REGION:local}

---
spring:
  config:
    activate:
      on-profile: test

auth:
  service:
    url: http://localhost:${wiremock.server.port}
